# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: aws configure set region $AWS_DEFAULT_REGION
      - run: aws ec2 run-instances --cli-input-yaml file://template.yaml # https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-skeleton.html


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  infrastructure_creation:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure
