# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name my-stack

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["07:ad:65:b2:6f:68:7a:b6:49:63:2c:14:76:15:12:69"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            apk add --no-cache openssh-client && ssh-keyscan 3.143.116.91 > ~/.ssh/known_hosts
            ansible-playbook -i inventory.txt playbook.yml
          # https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Check if website responds
          command: |
            if curl -s --head "https://google.com"
            then
              echo "It worked!"
            else
             echo "It failed."
            fi

# Orchestrate or schedule a set of jobs
workflows:
  infrastructure_creation:
    jobs:
      # - create_infrastructure
      # - configure_infrastructure
      - smoke_test
